# This chart values are not really flexible or production-ready.
# Its main use is to showcase supporting infrastructure being deployed alongside the main workload.
shared:
  releaseName: ""
  labels:
    team: platform
    awesome: totally

deployment:
  replicaCount: 1
  image: ""
  targetPort: 80

ingress:
  enabled: false
  host: ""