{{- if .Values.bucket.enabled -}}
apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  name: {{ .Values.bucket.nameOverride | default .Values.shared.releaseName }}
  labels: {{ .Values.shared.labels | toYaml | nindent 4 }}
    app: {{ .Values.shared.releaseName }}
spec:
  {{- /* no support for delete actions. Again, just an example */}}
  {{- if .Values.bucket.lifecycleRules }}
  lifecycleRule:
    {{- range .Values.bucket.lifecycleRules }}
    {{- range $storageClass, $age := . }}
    - action: 
        type: SetStorageClass
        storageClass: {{ $storageClass }}
      condition:
        age:  {{ $age }}
    {{- end }}
    {{- end }}
  {{- end }}
  versioning:
    enabled: {{ .Values.bucket.versioning }}
{{- end }}