apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}
  labels: {{ .Values.shared.labels | toYaml | nindent 4 }}
    app: {{ .Release.Name }}
spec:
  replicas: {{ .Values.deployment.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}
  template:
    metadata:
      labels: {{ .Values.shared.labels | toYaml | nindent 8 }}
        app: {{ .Release.Name }}
    spec:
      containers:
      - name: main
        image: {{ .Values.deployment.image }}
        imagePullPolicy: Always
        {{- if .Values.deployment.args }}
        args: {{ .Values.deployment.args }}
        {{- end }}
        {{- if .Values.deployment.resources }}
        resources: {{ .Values.deployment.resources | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.deployment.readinessProbe }}
        readinessProbe: {{ .Values.deployment.readinessProbe | toYaml | nindent 10 }}
        {{- end }}
        {{- if .Values.deployment.env }}
        env: {{ .Values.deployment.env | toYaml | nindent 10 }}
        {{- end }}
        ports:
        - name: http
          containerPort: {{ .Values.deployment.targetPort }}
          protocol: TCP
        volumeMounts:
          - name: identity
            mountPath: /etc/identity
            readOnly: true
      volumes:
        - name: identity
          secret:
            secretName: helm-{{ .Release.Name }}-key # TODO: correct interpolation to work with pre-existing svc accounts