{{- if .Values.publicAccess.enabled -}}
apiVersion: networking.k8s.io/v1beta1
kind: Ingress
metadata:
  name: {{ .Release.Name }}
  labels: {{ .Values.shared.labels | toYaml | nindent 4 }}
  annotations:
    kubernetes.io/ingress.global-static-ip-name: {{ .Release.Name }}
spec:
  rules:
  - host: {{ .Values.publicAccess.nameOverride | default (printf "%s.%s" .Release.Name .Values.shared.networking.fullyQualifiedDomainName) }}
    http:
      paths:
      - backend:
          serviceName: {{ .Release.Name }}
          servicePort: 80
{{- end -}}