{{- if .Values.publicAccess.enabled -}}
apiVersion: compute.cnrm.cloud.google.com/v1beta1
kind: ComputeAddress
metadata:
  name: {{ .Release.Name }}
  labels: {{ .Values.shared.labels | toYaml | nindent 4 }}
    app: {{ .Release.Name }}
spec:
  addressType: EXTERNAL
  description: "Global static address for {{ .Release.Name }}"
  location: global
{{- end -}}