{{- if .Values.messageTopicSubscription.enabled -}}
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  name: {{ .Release.Name }}
  labels: {{ .Values.shared.labels | toYaml | nindent 4 }}
    app: {{ .Release.Name }}
spec:
  ackDeadlineSeconds: 15
  messageRetentionDuration: 3600s
  retainAckedMessages: false
  topicRef:
    name: {{ .Values.messageTopicSubscription.topicName }}
{{- end -}}