{{- if .Values.identity.enabled -}}
{{- $svcAccountName := .Values.identity.nameOverride | default (printf "helm-%s" .Values.shared.releaseName) -}}
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: {{ $svcAccountName }}
  labels: {{ .Values.shared.labels | toYaml | nindent 4 }}
    app: {{ .Values.shared.releaseName }}
spec:
  description: "Identity for the Helm release: {{ .Values.shared.releaseName }}"
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccountKey
metadata:
  name: {{ $svcAccountName }}-key
  labels: {{ .Values.shared.labels | toYaml | nindent 4 }}
    app: {{ .Values.shared.releaseName }}
spec:
  serviceAccountRef:
    name: {{ $svcAccountName }}
{{- end }}
