{{- if .Values.identity.enabled -}}
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: "helm-{{ .Values.identity.nameOverride | default .Values.shared.releaseName }}"
  labels: {{ .Values.shared.labels | toYaml | nindent 4 }}
    app: {{ .Values.shared.releaseName }}
spec:
  description: "Identity for the Helm release: {{ .Values.shared.releaseName }}"
{{- end }}
