{{- $svcAccountName := printf "helm-%s" .Values.shared.releaseName }}
{{- if .Values.identity.createSvcAccount }}
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccount
metadata:
  name: {{ $svcAccountName }}
  labels: {{ .Values.shared.labels | toYaml | nindent 4 }}
    app: {{ .Values.shared.releaseName }}
spec:
  displayName: {{ $svcAccountName }}
  description: "Identity for the Helm release: {{ .Values.shared.releaseName }}"
{{- else -}}
{{- $svcAccountName = .Values.identity.existingSvcAccountName }}
{{- end }}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMServiceAccountKey
metadata:
  name: {{ $svcAccountName }}-key
  labels: {{ .Values.shared.labels | toYaml | nindent 4 }}
    app: {{ .Values.shared.releaseName }}
spec:
  serviceAccountRef:
    {{- if .Values.identity.createSvcAccount }}
    name: {{ $svcAccountName }}
    {{- else }}
    external: projects/{{ .Values.shared.projectName }}/serviceAccounts/{{ $svcAccountName }}
    {{- end }}
