## Calling this 'hacks' didn't sound as nice
shared:
  projectName: "lorenzo-scratch-space"
  networking:
    managedDNSZoneName: "playground"
    staticIPAddress: "35.244.190.237"
    staticIPName: "webserver-static-address"

## Vanilla Kubernetes deployment
deployment:
  replicaCount: 3
  image: "eu.gcr.io/lorenzo-scratch-space/webserver"
  targetPort: 8000
  env: 
    - name: FLASK_RUN_PORT
      value: "8000"
  readinessProbe:
    initialDelaySeconds: 15
    periodSeconds: 5
    httpGet:
      path: /ready
      port: 8000
  resources:
    requests:
      cpu: "500m"
      memory: "2Gi"
    limits:
      cpu: "500m"
      memory: "2Gi"

## Infrastructure provisioning.
# The svc account key is available to container under /etc/identity/key.json and GOOGLE_APPLICATION_CREDENTIALS is set
publicUrl:
  enabled: true
  nameOverride: "twitter.playground.robota.dev"

messageTopic:
  enabled: true
  nameOverride: "queued-tweets"
