{{- if .Values.bucket.enabled -}}
apiVersion: storage.cnrm.cloud.google.com/v1beta1
kind: StorageBucket
metadata:
  name: {{ .Values.bucket.nameOverride | default .Release.Name }}
  labels: {{ .Values.shared.labels | toYaml | nindent 4 }}
    app: {{ .Release.Name }}
spec:
  {{- /* no support for delete actions. Again, just an example */}}
  {{- if .Values.bucket.lifecycleRules }}
  lifecycleRule:
    {{- range .Values.bucket.lifecycleRules }}
    {{- range $storageClass, $age := . }}
    - action: 
        type: SetStorageClass
        storageClass: {{ $storageClass }}
      condition:
        age:  {{ $age }}
    {{- end }}
    {{- end }}
  {{- end }}
  versioning:
    enabled: {{ .Values.bucket.versioning }}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: "{{ .Values.messageTopic.nameOverride | default .Release.Name }}-bucket"
  labels: {{ .Values.shared.labels | toYaml | nindent 4 }}
    app: {{ .Release.Name }}
spec:
  resourceRef:
    apiVersion: storage.cnrm.cloud.google.com/v1beta1
    kind: StorageBucket
    name: {{ .Values.bucket.nameOverride | default .Release.Name }}
  role: roles/storage.objectCreator
  member: serviceAccount:helm-{{ .Release.Name }}@{{ .Values.shared.projectName }}.iam.gserviceaccount.com
{{- end -}}