{{- if .Values.publicUrl.enabled -}}
apiVersion: dns.cnrm.cloud.google.com/v1beta1
kind: DNSRecordSet
metadata:
  name: {{ .Release.Name }}
  labels: {{ .Values.shared.labels | toYaml | nindent 4 }}
    app: {{ .Release.Name }}
spec:
  name: "{{ .Values.publicUrl.nameOverride | default (printf "%s.%s" .Release.Name .Values.shared.networking.fullyQualifiedDomainName) }}."
  type: "A"
  ttl: 300
  managedZoneRef:
    external: {{ .Values.shared.networking.managedDNSZoneName }}
  rrdatas:
  - {{ .Values.shared.networking.staticIPAddress }}
{{- end -}}