{{- if .Values.messageTopicSubscription.enabled -}}
apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
kind: PubSubSubscription
metadata:
  name: {{ .Release.Name }}
  labels: {{ .Values.shared.labels | toYaml | nindent 4 }}
    app: {{ .Release.Name }}
spec:
  ackDeadlineSeconds: 15
  messageRetentionDuration: 3600s
  retainAckedMessages: false
  topicRef:
    name: {{ .Values.messageTopicSubscription.topicName }}
---
apiVersion: iam.cnrm.cloud.google.com/v1beta1
kind: IAMPolicyMember
metadata:
  name: "{{ .Values.messageTopic.nameOverride | default .Release.Name }}-pubsub-subscription"
  labels: {{ .Values.shared.labels | toYaml | nindent 4 }}
    app: {{ .Release.Name }}
spec:
  resourceRef:
    apiVersion: pubsub.cnrm.cloud.google.com/v1beta1
    kind: PubSubTopic
    name: {{ .Values.messageTopic.nameOverride | default .Release.Name }}
  role: roles/pubsub.subscriber
  member: serviceAccount:helm-{{ .Release.Name }}@{{ .Values.shared.projectName }}.iam.gserviceaccount.com
{{- end -}}